/**
 * この package は元々 protocol.ts の型だけ (runtime export ゼロ = import が完全に消える) だったが、
 * 2026-07-25 (リファクタリング フェーズ4) に work-log.ts で runtime の純関数を持つようになった。
 * ビルド構成の変更は不要 (package.json の main/exports が src/index.ts を直接指しており、
 * vite / wrangler がそれぞれのアプリのバンドルに TS ソースとして取り込む) — その代わり、ここに
 * 置くコードは web (DOM) と sync (Workers) の**両方の tsconfig**で通る環境非依存な純関数に限る。
 */
export {
  aggregateWorkLogEntries,
  formatDurationHm,
  validateWorkLogInterval,
  workLogIssueIdentity,
} from "./work-log";
export type {
  WorkLogAggregateBucket,
  WorkLogAggregateEntry,
  WorkLogIssueIdentity,
  WorkLogValidationError,
} from "./work-log";

export type {
  AccountDTO,
  DisconnectRequest,
  ApiError,
  CalendarListEntryDTO,
  GoogleEventDTO,
  MeResponse,
  VisibleCalendarsRequest,
  SyncRequest,
  ServerEvent,
  EventPatchRequest,
  EventPatchResponse,
  RsvpResponseStatus,
  EventRsvpRequest,
  EventRsvpResponse,
  EventCreateRequest,
  EventCreateResponse,
  EventDeleteRequest,
  EventDeleteResponse,
  TaskListDTO,
  GoogleTaskDTO,
  TaskListsResponse,
  TasksSyncRequest,
  TasksSyncResponse,
  TaskPatchRequest,
  TaskPatchResponse,
  BlockMode,
  BlockRuleDTO,
  BlockRulesResponse,
  BlockRuleUpsertRequest,
  BlockRuleDeleteRequest,
  WatchRequest,
  SyncResponse,
  GitHubConnectionDTO,
  GitHubItemType,
  GitHubItemDTO,
  GitHubItemsResponse,
  GitHubWorkKind,
  GitHubWorkItemDTO,
  GitHubQueueResponse,
  GitHubActivityType,
  GitHubActivityDTO,
  GitHubActivityResponse,
  GitHubCiStatus,
  GitHubCiConclusion,
  GitHubCiRunDTO,
  GitHubCiRunsResponse,
  PullCommitsRequest,
  PullCommitsResponse,
  GitHubRepoRef,
  GitHubReposResponse,
  GitHubRepoIssue,
  GitHubRepoIssuesResponse,
  McpTokenDTO,
  McpTokensResponse,
  McpTokenCreateRequest,
  McpTokenCreateResponse,
  McpTokenDeleteRequest,
  WorkIntervalRequest,
  WorkIntervalResponse,
  WorkLogDTO,
  WorkLogsResponse,
  WorkLogCreateRequest,
  WorkLogCreateResponse,
  WorkLogUpdateRequest,
  WorkIntervalStartRequest,
  WorkIntervalStartResponse,
  WorkIntervalStopRequest,
  WorkIntervalStopResponse,
  OpenWorkIntervalDTO,
  OpenWorkIntervalsResponse,
} from "./protocol";
